### ISSUE TITLE
Unable to create config file

### ISSUE THREAD

**Issue by BirjuVachhani** [BirjuVachhani/spider#7]
version `0.3.0`

An error occurred while executing `spider create` command. see stack trace:

```
Unhandled exception:
FileSystemException: Cannot copy file to 'spider.yaml', path = 'C:\config.yaml' (OS Error: The system cannot find the file specified.
, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.copySync (dart:io/file_impl.dart:350:5)
#2      Spider.createConfigs (package:spider/spider.dart:58:17)
#3      processCreateCommand (file:///C:/Users/brvac/AppData/Roaming/Pub/Cache/git/spider-8ecc3cf52c8101dce0160ce749f5f94896b7c3bc/bin/main.dart:
155:12)
#4      main (file:///C:/Users/brvac/AppData/Roaming/Pub/Cache/git/spider-8ecc3cf52c8101dce0160ce749f5f94896b7c3bc/bin/main.dart:58:9)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
Unhandled exception:
FileSystemException: Cannot copy file to 'spider.yaml', path = 'C:\config.yaml' (OS Error: The system cannot find the file specified.
, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.copySync (dart:io/file_impl.dart:350:5)
#2      Spider.createConfigs (package:spider/spider.dart:58:17)
#3      processCreateCommand (file:///C:/Users/brvac/AppData/Roaming/Pub/Cache/git/spider-8ecc3cf52c8101dce0160ce749f5f94896b7c3bc/bin/main.dart:
155:12)
#4      main (file:///C:/Users/brvac/AppData/Roaming/Pub/Cache/git/spider-8ecc3cf52c8101dce0160ce749f5f94896b7c3bc/bin/main.dart:58:9)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

**Comment by BirjuVachhani** [comment]
This seems to be happening because it cannot find `config.yaml` file which is a template file for creating new configs.
